### ISSUE TITLE
fix: 닫기버튼 수정, 헤더 변경, 이번달 버튼 css 수정

### ISSUE THREAD

**Issue by anhyeryeon2** [Dev-FE-2/toy-project2-team2#56]
## 📄 Describe

- 닫기버튼 1개로만 수정하고, 헤더 변경, 이번달 버튼 css 수정하겠습니다 ~

## ✅ Tasks

- [x] 월별 급여 닫기버튼
- [x] 정정 내역 모달 닫기버튼 
- [x] 헤더 변경
- [x] 급여내역 조회 - 이번달 버튼

## 📋 Ref

추가적인 정보나 참고 문서를 적어요.
